apiVersion: v1
data:
  config.yml: |-
    exposer: Ingress
    domain: test.zendy.io
    http: true
    tls-acme: false
    urltemplate: "{{ .Values.urltemplate }}"
kind: ConfigMap
metadata:
  name: exposecontroller