dependencies:
- name: zendy-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.0.0-rc.20
- name: zendy-cockpit
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.0.0-rc.11
- name: zendy-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.02
